export MODEL_NAME="stabilityai/stable-diffusion-2-inpainting"
export INSTANCE_DIR="data/celebahq/IDI/idi_5/0003/ref_image"
export OUTPUT_DIR="expr/celebahq/SDI2_LORA/0003"

lora_pti \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --train_inpainting \
  --cached_latents=False \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=2 \
  --gradient_checkpointing \
  --scale_lr \
  --learning_rate_unet=2e-4 \
  --learning_rate_text=1e-6 \
  --learning_rate_ti=5e-4 \
  --color_jitter \
  --lr_scheduler="linear" \
  --lr_warmup_steps=0 \
  --lr_scheduler_lora="constant" \
  --lr_warmup_steps_lora=100 \
  --placeholder_tokens="<person>" \
  --save_steps=10000 \
  --max_train_steps_ti=1000 \
  --max_train_steps_tuning=3000 \
  --perform_inversion=True \
  --clip_ti_decay \
  --weight_decay_ti=0.000 \
  --weight_decay_lora=0.000 \
  --device="cuda:1" \
  --lora_rank=8 \
  --lora_dropout_p=0.1 \
  --lora_scale=2.0 \
